version: "2"
services:
  # The Application
  app:
    tty: true
    image: laravel-app:20210926
    container_name: laravel.app
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - database
    networks:
      - laravel-demo-net
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_USERNAME=postgres
      - DB_DATABASE=laravel-demo
      - DB_PASSWORD=123456
      - TZ=Asia/Shanghai

  # The Web Server
  web:
    image: nginx
    container_name: laravel.web
    working_dir: /var/www
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    ports:
      - 8080:80
    networks:
      - laravel-demo-net

  # The Database
  database:
    image: postgres:13
    container_name: laravel.db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: laravel-demo
    ports:
      - "5432:5432"
    networks:
      - laravel-demo-net
    volumes:
      - laravel-demo-db:/var/lib/postgres
    # privileged: true # Privileged mode could be required to run this container under Windows

volumes:
  laravel-demo-db:
networks:
  laravel-demo-net:
    external: true
